apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-config
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  PROJECT_NAME: "OmniForge Multimodal Intelligence Platform"
  LOG_LEVEL: "INFO"
  API_V1_STR: "/api/v1"
  REDIS_URL: "redis://{{ .Release.Name }}-redis-master:6379/0"
  DATABASE_URL: "postgresql+asyncpg://omniforge_user:omniforge_password@{{ .Release.Name }}-postgresql:5432/omniforge_db"
  ARTIFACT_STORAGE_PATH: {{ .Values.persistence.artifacts.mountPath | quote }}
  DATASET_STORAGE_PATH: {{ .Values.persistence.datasets.mountPath | quote }}
