apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  SECRET_KEY: "omniforge-production-enterprise-jwt-super-secret-key-32bytes"
  POSTGRES_PASSWORD: "omniforge_password"
